"""
Slide theme definitions — 11 distinct visual styles.

Each theme is a dict that drives every colour and effect decision in the
slide renderer and component system.
"""

from __future__ import annotations
from typing import Dict, Any, List


SLIDE_THEMES: Dict[str, Dict[str, Any]] = {

    # ── 1. Dark Modern ────────────────────────────────────────────────────────
    # GitHub / VS Code dark — the developer's default
    "dark_modern": {
        "name": "Dark Modern",
        "desc": "GitHub-inspired dark theme — clean and professional",
        # Background
        "bg_type": "gradient",
        "bg_colors": ["#0d1117", "#161b22"],
        "gradient_direction": "vertical",
        # Text
        "title_color": "#f0f6fc",
        "subtitle_color": "#7d8590",
        "body_color": "#c9d1d9",
        "footer_color": "#484f58",
        "watermark_color": "#30363d",
        # Accent
        "accent_color": "#58a6ff",
        "accent_alt": "#3fb950",
        "tag_bg": "#1f6feb",
        "tag_fg": "#cae8ff",
        # Cards
        "card_style": "solid",
        "card_bg": "#161b22",
        "card_border": "#30363d",
        "card_radius": 12,
        "card_shadow": True,
        # Code
        "code_bg": "#0d1117",
        "code_border": "#30363d",
        "code_text": "#c9d1d9",
        "code_line_num": "#484f58",
        "keyword": "#ff7b72",
        "string": "#a5d6ff",
        "comment": "#8b949e",
        "number": "#f2cc60",
        "builtin": "#d2a8ff",
        "operator": "#79c0ff",
        "function": "#d2a8ff",
        # Terminal
        "terminal_bg": "#010409",
        "terminal_border": "#30363d",
        "terminal_text": "#3fb950",
        "terminal_prompt": "#58a6ff",
        "terminal_error": "#ff7b72",
        # Effects
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": [],
        # Layout
        "header_line": True,
        "step_circle_fill": "#1f6feb",
        "step_circle_text": "#ffffff",
        "progress_track": "#21262d",
        "progress_fill": "#58a6ff",
        "bullet_char": "▶",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 60,
    },

    # ── 2. Glassmorphism ──────────────────────────────────────────────────────
    "glassmorphism": {
        "name": "Glassmorphism",
        "desc": "Frosted glass cards on deep purple-blue gradient",
        "bg_type": "gradient",
        "bg_colors": ["#1a1a40", "#0d0d2b", "#1a0a30"],
        "gradient_direction": "diagonal",
        "title_color": "#ffffff",
        "subtitle_color": "#b4b4e0",
        "body_color": "#d0d0f0",
        "footer_color": "#7070a0",
        "watermark_color": "#3030604",
        "accent_color": "#7c3aed",
        "accent_alt": "#06b6d4",
        "tag_bg": "#7c3aed",
        "tag_fg": "#ffffff",
        "card_style": "glass",
        "card_bg": "#ffffff",
        "card_border": "#ffffff",
        "card_radius": 20,
        "card_shadow": False,
        "glass_blur": 20,
        "glass_tint_alpha": 25,
        "glass_border_alpha": 70,
        "code_bg": "#1a1a40",
        "code_border": "#7c3aed",
        "code_text": "#e0e0ff",
        "code_line_num": "#5050a0",
        "keyword": "#e879f9",
        "string": "#6ee7b7",
        "comment": "#818cf8",
        "number": "#fbbf24",
        "builtin": "#f472b6",
        "operator": "#67e8f9",
        "function": "#a78bfa",
        "terminal_bg": "#0d0d2b",
        "terminal_border": "#7c3aed",
        "terminal_text": "#6ee7b7",
        "terminal_prompt": "#a78bfa",
        "terminal_error": "#f87171",
        "glow_effects": True,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": True,
        "accent_bar_bottom": False,
        "decorations": ["particles"],
        "header_line": False,
        "step_circle_fill": "#7c3aed",
        "step_circle_text": "#ffffff",
        "progress_track": "#2d2d5b",
        "progress_fill": "#7c3aed",
        "bullet_char": "◆",
        "check_char_done": "✦",
        "check_char_todo": "◇",
        "divider_opacity": 40,
    },

    # ── 3. Cyberpunk ──────────────────────────────────────────────────────────
    "cyberpunk": {
        "name": "Cyberpunk",
        "desc": "Neon magenta & cyan on black — sci-fi hacker aesthetic",
        "bg_type": "gradient",
        "bg_colors": ["#000000", "#0d0020", "#00000d"],
        "gradient_direction": "diagonal",
        "title_color": "#ff00ff",
        "subtitle_color": "#00ffff",
        "body_color": "#e0e0e0",
        "footer_color": "#606060",
        "watermark_color": "#202020",
        "accent_color": "#ff00ff",
        "accent_alt": "#00ffff",
        "tag_bg": "#ff00ff",
        "tag_fg": "#000000",
        "card_style": "solid",
        "card_bg": "#0d0d0d",
        "card_border": "#ff00ff",
        "card_radius": 4,
        "card_shadow": True,
        "code_bg": "#0a0a0a",
        "code_border": "#00ffff",
        "code_text": "#e0e0e0",
        "code_line_num": "#404040",
        "keyword": "#ff00ff",
        "string": "#00ff41",
        "comment": "#606060",
        "number": "#ffff00",
        "builtin": "#00ffff",
        "operator": "#ff6600",
        "function": "#00ffff",
        "terminal_bg": "#000000",
        "terminal_border": "#00ff41",
        "terminal_text": "#00ff41",
        "terminal_prompt": "#00ffff",
        "terminal_error": "#ff0000",
        "glow_effects": True,
        "show_scanlines": True,
        "show_grid": False,
        "show_particles": True,
        "accent_bar_bottom": True,
        "decorations": ["scanlines", "particles"],
        "header_line": True,
        "step_circle_fill": "#ff00ff",
        "step_circle_text": "#000000",
        "progress_track": "#1a001a",
        "progress_fill": "#ff00ff",
        "bullet_char": "▷",
        "check_char_done": "✔",
        "check_char_todo": "□",
        "divider_opacity": 80,
    },

    # ── 4. Educational ────────────────────────────────────────────────────────
    "educational": {
        "name": "Educational",
        "desc": "Warm ocean gradient — friendly and approachable",
        "bg_type": "gradient",
        "bg_colors": ["#1a6985", "#2193b0", "#6dd5ed"],
        "gradient_direction": "diagonal",
        "title_color": "#ffffff",
        "subtitle_color": "#fff9c4",
        "body_color": "#e8f4f8",
        "footer_color": "#9dd4e8",
        "watermark_color": "#1a6985",
        "accent_color": "#ff9800",
        "accent_alt": "#4caf50",
        "tag_bg": "#ff9800",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#1a6985",
        "card_border": "#ffffff",
        "card_radius": 16,
        "card_shadow": True,
        "code_bg": "#0d3a4d",
        "code_border": "#2193b0",
        "code_text": "#e8f4f8",
        "code_line_num": "#4a8fa0",
        "keyword": "#ffcc02",
        "string": "#a5f3a5",
        "comment": "#90c4d0",
        "number": "#ffb347",
        "builtin": "#90caf9",
        "operator": "#ff9800",
        "function": "#90caf9",
        "terminal_bg": "#0d2a35",
        "terminal_border": "#2193b0",
        "terminal_text": "#a5f3a5",
        "terminal_prompt": "#ffcc02",
        "terminal_error": "#ff7043",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": [],
        "header_line": True,
        "step_circle_fill": "#ff9800",
        "step_circle_text": "#ffffff",
        "progress_track": "#0d3a4d",
        "progress_fill": "#ff9800",
        "bullet_char": "●",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 70,
    },

    # ── 5. Minimal ────────────────────────────────────────────────────────────
    "minimal": {
        "name": "Minimal",
        "desc": "Apple-style clean white — distraction-free",
        "bg_type": "solid",
        "bg_colors": ["#f5f5f7"],
        "gradient_direction": "horizontal",
        "title_color": "#1d1d1f",
        "subtitle_color": "#6e6e73",
        "body_color": "#3c3c43",
        "footer_color": "#8e8e93",
        "watermark_color": "#d1d1d6",
        "accent_color": "#0071e3",
        "accent_alt": "#34c759",
        "tag_bg": "#0071e3",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#ffffff",
        "card_border": "#e5e5ea",
        "card_radius": 14,
        "card_shadow": True,
        "code_bg": "#1c1c1e",
        "code_border": "#2c2c2e",
        "code_text": "#f2f2f7",
        "code_line_num": "#636366",
        "keyword": "#ff375f",
        "string": "#30d158",
        "comment": "#8e8e93",
        "number": "#ff9f0a",
        "builtin": "#0071e3",
        "operator": "#5e5ce6",
        "function": "#0071e3",
        "terminal_bg": "#1c1c1e",
        "terminal_border": "#2c2c2e",
        "terminal_text": "#30d158",
        "terminal_prompt": "#0071e3",
        "terminal_error": "#ff375f",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": False,
        "decorations": [],
        "header_line": False,
        "step_circle_fill": "#0071e3",
        "step_circle_text": "#ffffff",
        "progress_track": "#e5e5ea",
        "progress_fill": "#0071e3",
        "bullet_char": "•",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 50,
    },

    # ── 6. Futuristic AI ──────────────────────────────────────────────────────
    "futuristic_ai": {
        "name": "Futuristic AI",
        "desc": "Deep space purple with violet glow — AI & ML content",
        "bg_type": "gradient",
        "bg_colors": ["#000000", "#0f0035", "#00001a"],
        "gradient_direction": "radial",
        "title_color": "#ffffff",
        "subtitle_color": "#b0b0ff",
        "body_color": "#9090cc",
        "footer_color": "#5050a0",
        "watermark_color": "#1a1a40",
        "accent_color": "#7c4dff",
        "accent_alt": "#00e5ff",
        "tag_bg": "#7c4dff",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#0a0020",
        "card_border": "#7c4dff",
        "card_radius": 14,
        "card_shadow": True,
        "code_bg": "#050015",
        "code_border": "#7c4dff",
        "code_text": "#b0b0ff",
        "code_line_num": "#3030608",
        "keyword": "#bd93f9",
        "string": "#50fa7b",
        "comment": "#6272a4",
        "number": "#ffb86c",
        "builtin": "#8be9fd",
        "operator": "#ff79c6",
        "function": "#8be9fd",
        "terminal_bg": "#000000",
        "terminal_border": "#7c4dff",
        "terminal_text": "#50fa7b",
        "terminal_prompt": "#bd93f9",
        "terminal_error": "#ff5555",
        "glow_effects": True,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": True,
        "accent_bar_bottom": True,
        "decorations": ["particles", "hex_pattern"],
        "header_line": True,
        "step_circle_fill": "#7c4dff",
        "step_circle_text": "#ffffff",
        "progress_track": "#0f0035",
        "progress_fill": "#7c4dff",
        "bullet_char": "◈",
        "check_char_done": "✦",
        "check_char_todo": "◇",
        "divider_opacity": 50,
    },

    # ── 7. Gaming ─────────────────────────────────────────────────────────────
    "gaming": {
        "name": "Gaming",
        "desc": "Deep purple gradient with orange neon — gaming content",
        "bg_type": "gradient",
        "bg_colors": ["#0f0c29", "#302b63", "#24243e"],
        "gradient_direction": "diagonal",
        "title_color": "#ffffff",
        "subtitle_color": "#ffd700",
        "body_color": "#d0d0ff",
        "footer_color": "#808080",
        "watermark_color": "#302b63",
        "accent_color": "#ff6b35",
        "accent_alt": "#ffd700",
        "tag_bg": "#ff6b35",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#1a1a3e",
        "card_border": "#ff6b35",
        "card_radius": 10,
        "card_shadow": True,
        "code_bg": "#0f0c29",
        "code_border": "#ff6b35",
        "code_text": "#d0d0ff",
        "code_line_num": "#404060",
        "keyword": "#ff6b35",
        "string": "#ffd700",
        "comment": "#606080",
        "number": "#00ff99",
        "builtin": "#00ccff",
        "operator": "#ff9966",
        "function": "#00ccff",
        "terminal_bg": "#050510",
        "terminal_border": "#ff6b35",
        "terminal_text": "#00ff99",
        "terminal_prompt": "#ffd700",
        "terminal_error": "#ff3333",
        "glow_effects": True,
        "show_scanlines": True,
        "show_grid": False,
        "show_particles": True,
        "accent_bar_bottom": True,
        "decorations": ["scanlines", "particles"],
        "header_line": True,
        "step_circle_fill": "#ff6b35",
        "step_circle_text": "#ffffff",
        "progress_track": "#1a1a3e",
        "progress_fill": "#ff6b35",
        "bullet_char": "▶",
        "check_char_done": "✔",
        "check_char_todo": "□",
        "divider_opacity": 70,
    },

    # ── 8. Apple Style ────────────────────────────────────────────────────────
    "apple_style": {
        "name": "Apple Style",
        "desc": "Dramatic keynote look — huge type on white",
        "bg_type": "solid",
        "bg_colors": ["#ffffff"],
        "gradient_direction": "horizontal",
        "title_color": "#000000",
        "subtitle_color": "#1d1d1f",
        "body_color": "#3c3c43",
        "footer_color": "#8e8e93",
        "watermark_color": "#e5e5ea",
        "accent_color": "#007aff",
        "accent_alt": "#ff3b30",
        "tag_bg": "#007aff",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#f2f2f7",
        "card_border": "#e5e5ea",
        "card_radius": 18,
        "card_shadow": True,
        "code_bg": "#1c1c1e",
        "code_border": "#000000",
        "code_text": "#f2f2f7",
        "code_line_num": "#48484a",
        "keyword": "#ff375f",
        "string": "#30d158",
        "comment": "#636366",
        "number": "#ff9f0a",
        "builtin": "#007aff",
        "operator": "#5e5ce6",
        "function": "#007aff",
        "terminal_bg": "#1c1c1e",
        "terminal_border": "#000000",
        "terminal_text": "#30d158",
        "terminal_prompt": "#007aff",
        "terminal_error": "#ff375f",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": [],
        "header_line": False,
        "step_circle_fill": "#007aff",
        "step_circle_text": "#ffffff",
        "progress_track": "#e5e5ea",
        "progress_fill": "#007aff",
        "bullet_char": "•",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 30,
    },

    # ── 9. Netflix Documentary ────────────────────────────────────────────────
    "netflix_doc": {
        "name": "Netflix Documentary",
        "desc": "Cinematic black with red accents — dramatic storytelling",
        "bg_type": "gradient",
        "bg_colors": ["#000000", "#0a0000", "#000000"],
        "gradient_direction": "radial",
        "title_color": "#ffffff",
        "subtitle_color": "#e50914",
        "body_color": "#cccccc",
        "footer_color": "#666666",
        "watermark_color": "#222222",
        "accent_color": "#e50914",
        "accent_alt": "#f5a623",
        "tag_bg": "#e50914",
        "tag_fg": "#ffffff",
        "card_style": "solid",
        "card_bg": "#141414",
        "card_border": "#e50914",
        "card_radius": 6,
        "card_shadow": True,
        "code_bg": "#0a0a0a",
        "code_border": "#e50914",
        "code_text": "#cccccc",
        "code_line_num": "#444444",
        "keyword": "#e50914",
        "string": "#f5a623",
        "comment": "#666666",
        "number": "#f5a623",
        "builtin": "#ff6b6b",
        "operator": "#ff4757",
        "function": "#ff6b6b",
        "terminal_bg": "#000000",
        "terminal_border": "#e50914",
        "terminal_text": "#cccccc",
        "terminal_prompt": "#e50914",
        "terminal_error": "#ff0000",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": [],
        "header_line": True,
        "step_circle_fill": "#e50914",
        "step_circle_text": "#ffffff",
        "progress_track": "#222222",
        "progress_fill": "#e50914",
        "bullet_char": "—",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 60,
    },

    # ── 10. Coding Tutorial ───────────────────────────────────────────────────
    "coding_tutorial": {
        "name": "Coding Tutorial",
        "desc": "Catppuccin Mocha — the developer's editor theme",
        "bg_type": "gradient",
        "bg_colors": ["#1e1e2e", "#181825"],
        "gradient_direction": "vertical",
        "title_color": "#cdd6f4",
        "subtitle_color": "#a6adc8",
        "body_color": "#cdd6f4",
        "footer_color": "#585b70",
        "watermark_color": "#313244",
        "accent_color": "#89b4fa",
        "accent_alt": "#a6e3a1",
        "tag_bg": "#89b4fa",
        "tag_fg": "#1e1e2e",
        "card_style": "solid",
        "card_bg": "#181825",
        "card_border": "#313244",
        "card_radius": 12,
        "card_shadow": True,
        "code_bg": "#11111b",
        "code_border": "#313244",
        "code_text": "#cdd6f4",
        "code_line_num": "#45475a",
        "keyword": "#cba6f7",       # Mauve
        "string": "#a6e3a1",        # Green
        "comment": "#6c7086",       # Overlay0
        "number": "#fab387",        # Peach
        "builtin": "#f38ba8",       # Red
        "operator": "#89dceb",      # Sky
        "function": "#89b4fa",      # Blue
        "terminal_bg": "#11111b",
        "terminal_border": "#313244",
        "terminal_text": "#a6e3a1",
        "terminal_prompt": "#89b4fa",
        "terminal_error": "#f38ba8",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": False,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": [],
        "header_line": True,
        "step_circle_fill": "#89b4fa",
        "step_circle_text": "#1e1e2e",
        "progress_track": "#313244",
        "progress_fill": "#89b4fa",
        "bullet_char": "◉",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 50,
    },

    # ── 11. Finance / Business ────────────────────────────────────────────────
    "finance": {
        "name": "Finance / Business",
        "desc": "Dark navy with gold accents — premium professional",
        "bg_type": "gradient",
        "bg_colors": ["#0a1628", "#1a2940", "#0a1628"],
        "gradient_direction": "vertical",
        "title_color": "#ffffff",
        "subtitle_color": "#ffd700",
        "body_color": "#a0b4c8",
        "footer_color": "#4a6480",
        "watermark_color": "#0f2040",
        "accent_color": "#ffd700",
        "accent_alt": "#4caf50",
        "tag_bg": "#ffd700",
        "tag_fg": "#0a1628",
        "card_style": "solid",
        "card_bg": "#0f2040",
        "card_border": "#ffd700",
        "card_radius": 8,
        "card_shadow": True,
        "code_bg": "#071020",
        "code_border": "#ffd700",
        "code_text": "#a0b4c8",
        "code_line_num": "#2a4060",
        "keyword": "#4caf50",
        "string": "#81c784",
        "comment": "#546e7a",
        "number": "#ffd700",
        "builtin": "#80cbc4",
        "operator": "#ffcc02",
        "function": "#80cbc4",
        "terminal_bg": "#050e1a",
        "terminal_border": "#ffd700",
        "terminal_text": "#4caf50",
        "terminal_prompt": "#ffd700",
        "terminal_error": "#f44336",
        "glow_effects": False,
        "show_scanlines": False,
        "show_grid": True,
        "show_particles": False,
        "accent_bar_bottom": True,
        "decorations": ["grid"],
        "header_line": True,
        "step_circle_fill": "#ffd700",
        "step_circle_text": "#0a1628",
        "progress_track": "#0f2040",
        "progress_fill": "#ffd700",
        "bullet_char": "◆",
        "check_char_done": "✓",
        "check_char_todo": "○",
        "divider_opacity": 50,
    },
}


def get_slide_theme(name: str) -> Dict[str, Any]:
    return SLIDE_THEMES.get(name, SLIDE_THEMES["dark_modern"])


def list_slide_themes() -> List[str]:
    return list(SLIDE_THEMES.keys())


SLIDE_THEME_META = {k: (v["name"], v["desc"]) for k, v in SLIDE_THEMES.items()}
