"""
Built-in theme presets.
Each entry maps directly onto ThumbnailConfig fields so it can be
unpacked with config.from_dict(THEMES[name]).
"""

from typing import Dict, Any, List

THEMES: Dict[str, Dict[str, Any]] = {

    # ── Gaming ────────────────────────────────────────────────────────────
    "gaming": {
        "theme": "gaming",
        "bg_type": "gradient",
        "bg_colors": ["#0f0c29", "#302b63", "#24243e"],
        "gradient_direction": "diagonal",
        "text_color": "#ffffff",
        "subtitle_color": "#ffd700",
        "accent_color": "#ff6b35",
        "label_bg_color": "#ff6b35",
        "label_text_color": "#ffffff",
        "font_style": "impact",
        "shadow": True,
        "shadow_color": "#ff000055",
        "shadow_offset_x": 6,
        "shadow_offset_y": 6,
        "shadow_blur": 18,
        "stroke": True,
        "stroke_color": "#000000",
        "stroke_width": 4,
        "overlay": True,
        "overlay_opacity": 25,
        "glow": True,
        "glow_color": "#ff6b35",
        "glow_radius": 24,
        "blur_bg": False,
        "positioning": "modern_youtube",
        "cinematic_bars": False,
    },

    # ── Tech ─────────────────────────────────────────────────────────────
    "tech": {
        "theme": "tech",
        "bg_type": "gradient",
        "bg_colors": ["#000000", "#0a0a2e", "#001a3a"],
        "gradient_direction": "vertical",
        "text_color": "#00d4ff",
        "subtitle_color": "#ffffff",
        "accent_color": "#0066ff",
        "label_bg_color": "#0066ff",
        "label_text_color": "#ffffff",
        "font_style": "bold",
        "shadow": True,
        "shadow_color": "#00d4ff33",
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "shadow_blur": 20,
        "stroke": False,
        "stroke_color": "#00d4ff",
        "stroke_width": 2,
        "overlay": True,
        "overlay_opacity": 20,
        "glow": True,
        "glow_color": "#00d4ff",
        "glow_radius": 28,
        "blur_bg": False,
        "positioning": "left_aligned",
        "cinematic_bars": False,
    },

    # ── Dark ─────────────────────────────────────────────────────────────
    "dark": {
        "theme": "dark",
        "bg_type": "gradient",
        "bg_colors": ["#111111", "#1c1c1c", "#252525"],
        "gradient_direction": "radial",
        "text_color": "#ffffff",
        "subtitle_color": "#aaaaaa",
        "accent_color": "#e63946",
        "label_bg_color": "#e63946",
        "label_text_color": "#ffffff",
        "font_style": "bold",
        "shadow": True,
        "shadow_color": "#00000099",
        "shadow_offset_x": 4,
        "shadow_offset_y": 4,
        "shadow_blur": 12,
        "stroke": False,
        "stroke_color": "#e63946",
        "stroke_width": 3,
        "overlay": False,
        "overlay_opacity": 0,
        "glow": False,
        "glow_color": "#e63946",
        "glow_radius": 16,
        "blur_bg": False,
        "positioning": "centered",
        "cinematic_bars": False,
    },

    # ── Minimal ───────────────────────────────────────────────────────────
    "minimal": {
        "theme": "minimal",
        "bg_type": "solid",
        "bg_colors": ["#f8f9fa"],
        "gradient_direction": "horizontal",
        "text_color": "#212529",
        "subtitle_color": "#6c757d",
        "accent_color": "#0d6efd",
        "label_bg_color": "#0d6efd",
        "label_text_color": "#ffffff",
        "font_style": "bold",
        "shadow": False,
        "shadow_color": "#00000033",
        "shadow_offset_x": 3,
        "shadow_offset_y": 3,
        "shadow_blur": 8,
        "stroke": False,
        "stroke_color": "#212529",
        "stroke_width": 2,
        "overlay": False,
        "overlay_opacity": 0,
        "glow": False,
        "glow_color": "#0d6efd",
        "glow_radius": 10,
        "blur_bg": False,
        "positioning": "left_aligned",
        "cinematic_bars": False,
    },

    # ── Cyberpunk ─────────────────────────────────────────────────────────
    "cyberpunk": {
        "theme": "cyberpunk",
        "bg_type": "gradient",
        "bg_colors": ["#0d0d0d", "#1a0030", "#000d1a"],
        "gradient_direction": "diagonal",
        "text_color": "#ff00ff",
        "subtitle_color": "#00ffff",
        "accent_color": "#ffff00",
        "label_bg_color": "#ff00ff",
        "label_text_color": "#000000",
        "font_style": "impact",
        "shadow": True,
        "shadow_color": "#ff00ff55",
        "shadow_offset_x": 5,
        "shadow_offset_y": 5,
        "shadow_blur": 20,
        "stroke": True,
        "stroke_color": "#ff00ff",
        "stroke_width": 3,
        "overlay": True,
        "overlay_opacity": 15,
        "glow": True,
        "glow_color": "#ff00ff",
        "glow_radius": 30,
        "blur_bg": False,
        "positioning": "centered",
        "cinematic_bars": False,
    },

    # ── Educational ───────────────────────────────────────────────────────
    "educational": {
        "theme": "educational",
        "bg_type": "gradient",
        "bg_colors": ["#2193b0", "#6dd5ed", "#1a6985"],
        "gradient_direction": "diagonal",
        "text_color": "#ffffff",
        "subtitle_color": "#fff9c4",
        "accent_color": "#ff9800",
        "label_bg_color": "#ff9800",
        "label_text_color": "#ffffff",
        "font_style": "bold",
        "shadow": True,
        "shadow_color": "#00000055",
        "shadow_offset_x": 4,
        "shadow_offset_y": 4,
        "shadow_blur": 10,
        "stroke": False,
        "stroke_color": "#ffffff",
        "stroke_width": 2,
        "overlay": False,
        "overlay_opacity": 0,
        "glow": False,
        "glow_color": "#ff9800",
        "glow_radius": 14,
        "blur_bg": False,
        "positioning": "modern_youtube",
        "cinematic_bars": False,
    },

    # ── Finance ───────────────────────────────────────────────────────────
    "finance": {
        "theme": "finance",
        "bg_type": "gradient",
        "bg_colors": ["#0f2027", "#203a43", "#2c5364"],
        "gradient_direction": "vertical",
        "text_color": "#ffffff",
        "subtitle_color": "#4caf50",
        "accent_color": "#ffd700",
        "label_bg_color": "#ffd700",
        "label_text_color": "#000000",
        "font_style": "bold",
        "shadow": True,
        "shadow_color": "#00000066",
        "shadow_offset_x": 4,
        "shadow_offset_y": 4,
        "shadow_blur": 12,
        "stroke": False,
        "stroke_color": "#ffd700",
        "stroke_width": 2,
        "overlay": True,
        "overlay_opacity": 25,
        "glow": False,
        "glow_color": "#ffd700",
        "glow_radius": 16,
        "blur_bg": False,
        "positioning": "left_aligned",
        "cinematic_bars": False,
    },

    # ── AI / Futuristic ───────────────────────────────────────────────────
    "ai_futuristic": {
        "theme": "ai_futuristic",
        "bg_type": "gradient",
        "bg_colors": ["#0f0035", "#1a0050", "#00001a"],
        "gradient_direction": "radial",
        "text_color": "#ffffff",
        "subtitle_color": "#b0b0ff",
        "accent_color": "#7c4dff",
        "label_bg_color": "#7c4dff",
        "label_text_color": "#ffffff",
        "font_style": "bold",
        "shadow": True,
        "shadow_color": "#7c4dff44",
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "shadow_blur": 22,
        "stroke": False,
        "stroke_color": "#7c4dff",
        "stroke_width": 2,
        "overlay": True,
        "overlay_opacity": 20,
        "glow": True,
        "glow_color": "#7c4dff",
        "glow_radius": 32,
        "blur_bg": False,
        "positioning": "cinematic",
        "cinematic_bars": True,
    },
}


def get_theme(name: str) -> Dict[str, Any]:
    """Return theme dict or empty dict if not found."""
    return THEMES.get(name, {})


def list_themes() -> List[str]:
    return list(THEMES.keys())


THEME_META = {
    "gaming":        ("Gaming",        "High-energy neon on deep purple/navy — MrBeast & FPS style"),
    "tech":          ("Tech",          "Cyan glow on near-black — programming & tutorial videos"),
    "dark":          ("Dark",          "Sleek red accent on charcoal — cinematic drama"),
    "minimal":       ("Minimal",       "Clean blue on white — clean modern aesthetic"),
    "cyberpunk":     ("Cyberpunk",     "Magenta & cyan neon on black — sci-fi vibe"),
    "educational":   ("Educational",   "Warm ocean gradient — friendly learning content"),
    "finance":       ("Finance",       "Deep teal with gold — professional money/business"),
    "ai_futuristic": ("AI/Futuristic", "Deep purple with violet glow — AI & future tech"),
}
